name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Rebuild better-sqlite3
        run: npx electron-rebuild -f -w better-sqlite3

      - name: Build Linux
        run: yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-AppImage
          path: dist/*.AppImage

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Rebuild better-sqlite3
        run: npx electron-rebuild -f -w better-sqlite3

      - name: Build Windows
        run: yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe