name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      ELECTRON_CACHE: $HOME/.cache/electron
      ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Forçar HTTPS no lugar de SSH
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build Linux
        run: yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-AppImage
          path: dist/*.AppImage

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Forçar HTTPS no lugar de SSH
        run: git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build Windows
        run: yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe